// Sample stock, illustrated with real reference photos (Wikimedia Commons,
// freely licensed) of the same make/model until real yard photos are
// supplied. Replace title/specs/price/img with real inventory as it changes —
// see README.md for details. `slug` powers each vehicle's own detail page
// and JSON-LD, so keep it unique and URL-safe.

function wikiImg(file, width) {
  return `https://commons.wikimedia.org/wiki/Special:FilePath/${file}?width=${width}`;
}

export const VEHICLES = [
  {
    id: "v1",
    slug: "toyota-land-cruiser-prado",
    title: "Toyota Land Cruiser Prado",
    category: "cars",
    year: "2016",
    mileage: "78,000 km",
    fuel: "Diesel",
    transmission: "Automatic",
    price: "Contact for Price",
    icon: "car",
    img: wikiImg("Toyota_Land_Cruiser_Prado_90_005.JPG", 900),
    imgAlt: "Toyota Land Cruiser Prado, a rugged SUV export",
  },
  {
    id: "v2",
    slug: "toyota-hiace-van-super-gl",
    title: "Toyota Hiace Van (Super GL)",
    category: "cars",
    year: "2015",
    mileage: "95,000 km",
    fuel: "Diesel",
    transmission: "Manual",
    price: "Contact for Price",
    icon: "van",
    img: wikiImg("Toyota_Hiace_H200_501.JPG", 900),
    imgAlt: "Toyota Hiace Super GL van",
  },
  {
    id: "v11",
    slug: "nissan-caravan-cargo-van",
    title: "Nissan Caravan Cargo Van",
    category: "cars",
    year: "2017",
    mileage: "61,000 km",
    fuel: "Petrol",
    transmission: "Automatic",
    price: "Contact for Price",
    icon: "van",
    img: wikiImg("Nissan_Caravan_E25_001.JPG", 900),
    imgAlt: "Nissan Caravan cargo van",
  },
  {
    id: "v3",
    slug: "isuzu-elf-dropside-cargo-truck",
    title: "Isuzu Elf Dropside Cargo Truck",
    category: "trucks",
    year: "2014",
    mileage: "110,000 km",
    fuel: "Diesel",
    transmission: "Manual",
    price: "Contact for Price",
    icon: "truck",
    img: wikiImg("Isuzu_Elf_NPR_Dropside_Cargo_Truck_2019.jpg", 900),
    imgAlt: "Isuzu Elf dropside cargo truck",
  },
  {
    id: "v4",
    slug: "mitsubishi-fuso-canter-box-truck",
    title: "Mitsubishi Fuso Canter Box Truck",
    category: "trucks",
    year: "2013",
    mileage: "128,000 km",
    fuel: "Diesel",
    transmission: "Manual",
    price: "Contact for Price",
    icon: "dumptruck",
    img: wikiImg("Mitsubishi_Fuso_Canter._Box_rigid_truck._Spielvogel.jpg", 900),
    imgAlt: "Mitsubishi Fuso Canter box truck",
  },
  {
    id: "v12",
    slug: "ud-trucks-nissan-diesel-cargo-truck",
    title: "UD Trucks (Nissan Diesel) Cargo Truck",
    category: "trucks",
    year: "2012",
    mileage: "135,000 km",
    fuel: "Diesel",
    transmission: "Manual",
    price: "Contact for Price",
    icon: "truck",
    img: wikiImg("Nissan.CW.340.Diesel.Truck.1.Cambodge.jpg", 900),
    imgAlt: "UD Trucks Nissan Diesel cargo truck",
  },
  {
    id: "v5",
    slug: "hino-liesse-ii-mini-bus",
    title: "Hino Liesse II Mini Bus",
    category: "buses",
    year: "2012",
    mileage: "142,000 km",
    fuel: "Diesel",
    transmission: "Automatic",
    price: "Contact for Price",
    icon: "bus",
    img: wikiImg("Hino_Liesse_II_103.JPG", 900),
    imgAlt: "Hino Liesse II mini bus",
  },
  {
    id: "v6",
    slug: "komatsu-hydraulic-excavator",
    title: "Komatsu Hydraulic Excavator",
    category: "machinery",
    year: "2011",
    mileage: "6,200 hrs",
    fuel: "Diesel",
    transmission: "-",
    price: "Contact for Price",
    icon: "excavator",
    img: wikiImg("Komatsu_excavator.jpg", 900),
    imgAlt: "Komatsu hydraulic excavator",
  },
  {
    id: "v7",
    slug: "kubota-wheel-loader-backhoe",
    title: "Kubota Wheel Loader / Backhoe",
    category: "machinery",
    year: "2013",
    mileage: "4,800 hrs",
    fuel: "Diesel",
    transmission: "-",
    price: "Contact for Price",
    icon: "loader",
    img: wikiImg("Kubota_tractor_with_front_loader_and_backhoe.jpg", 900),
    imgAlt: "Kubota wheel loader and backhoe",
  },
  {
    id: "v8",
    slug: "industrial-diesel-generator-set",
    title: "Industrial Diesel Generator Set",
    category: "generators",
    year: "2015",
    mileage: "3,100 hrs",
    fuel: "Diesel",
    transmission: "-",
    price: "Contact for Price",
    icon: "generator",
    img: wikiImg("Diesel_generator.jpg", 900),
    imgAlt: "Industrial diesel generator set",
  },
  {
    id: "v9",
    slug: "yanmar-agricultural-tractor",
    title: "Yanmar Agricultural Tractor",
    category: "tractors",
    year: "2012",
    mileage: "3,900 hrs",
    fuel: "Diesel",
    transmission: "Manual",
    price: "Contact for Price",
    icon: "tractor",
    img: wikiImg("Yanmar_YM_1601_D.jpg", 900),
    imgAlt: "Yanmar agricultural tractor",
  },
  {
    id: "v10",
    slug: "rice-combine-harvester",
    title: "Rice Combine Harvester",
    category: "tractors",
    year: "2010",
    mileage: "2,600 hrs",
    fuel: "Diesel",
    transmission: "Manual",
    price: "Contact for Price",
    icon: "tractor",
    img: wikiImg("Rice-combine-harvester%2C_Katori-city%2C_Japan.jpg", 900),
    imgAlt: "Rice combine harvester",
  },
];

export function getVehicleBySlug(slug) {
  return VEHICLES.find((v) => v.slug === slug);
}
