// Showroom stock. Photos live in /public/cars/<slug>/NN.jpg (order = gallery
// order, first image is the cover). Facts marked "sheet" come from the
// Japanese auction sheet the client supplied; "factory" values are the
// manufacturer's published figures for that model, not measured on this car.
// To add a car: drop its photos in public/cars/<slug>/, then add an entry here.

const cars = (slug, captions) =>
  captions.map(([alt, kind], i) => ({
    src: `/cars/${slug}/${String(i + 1).padStart(2, "0")}.jpg`,
    alt,
    kind: kind || "photo",
  }));

export const VEHICLES = [
  {
    id: "PT-001",
    slug: "toyota-land-cruiser-prado-tx-tss-4wd",
    make: "Toyota",
    model: "Land Cruiser Prado",
    grade: "TX T-Spec Safety System 4WD",
    title: "Toyota Land Cruiser Prado TX 4WD",
    type: "SUV",
    year: 2022,
    registered: "September 2022",
    mileageKm: 27384,
    mileage: "27,384 km",
    fuel: "Petrol",
    transmission: "Automatic",
    drive: "4WD",
    engine: "2.7L (2,700 cc) petrol",
    chassis: "TRJ150W",
    seats: 7,
    color: "Pearl White",
    steering: "Right-hand drive",
    auctionGrade: "4.5 (interior B)",
    badge: "Low mileage",
    price: null,
    summary:
      "A near-new, seven-seat Prado in Pearl White with permanent four-wheel drive, Toyota Safety Sense, a factory-style Modellista aero kit and a full multimedia navigation system. Just 27,384 km and graded 4.5 at auction.",
    highlights: ["Only 27,384 km", "Grade 4.5 auction rating", "7 seats, 4WD", "Modellista aero kit"],
    features: [
      "4WD (part-time selectable)",
      "Seven-seat three-row layout",
      "Alpine navigation with TV",
      "Back camera",
      "ETC (electronic toll) unit",
      "LED headlights",
      "Clearance sonar",
      "ABS and airbags",
      "Power steering and windows",
      "Automatic air conditioning",
      "Modellista aero parts",
      "Toyota Safety Sense (TSS)",
    ],
    specs: [
      ["Make / model", "Toyota Land Cruiser Prado"],
      ["Grade", "TX T-Spec Safety System 4WD"],
      ["Chassis code", "3BA-TRJ150W"],
      ["First registered", "September 2022"],
      ["Mileage", "27,384 km (sheet)"],
      ["Engine", "2.7L petrol, 2TR-FE (2,700 cc)"],
      ["Transmission", "Automatic (6-speed, floor shift)"],
      ["Drive", "4WD"],
      ["Seats", "7"],
      ["Colour", "Pearl White (070)"],
      ["Steering", "Right-hand drive"],
      ["Auction grade", "4.5 / interior B"],
    ],
    photos: cars("toyota-land-cruiser-prado-tx-tss-4wd", [
      ["Toyota Land Cruiser Prado in Pearl White, front three-quarter view"],
      ["Toyota Land Cruiser Prado rear three-quarter view with spoiler"],
      ["Prado driver cockpit with leather steering wheel and instruments"],
      ["Prado front cabin, centre console and gear selector"],
      ["Prado front seat in black fabric"],
      ["Prado second-row bench seat"],
      ["Alpine navigation screen in the Prado dashboard"],
      ["Prado driver-side switch panel"],
      ["Prado underbody, front skid plate"],
      ["Prado underbody, rear axle and spare wheel"],
      ["Prado underbody, exhaust and transfer case"],
      ["Japanese auction inspection sheet for the Prado", "sheet"],
    ]),
  },
  {
    id: "PT-002",
    slug: "toyota-yaris-hybrid-x-2021",
    make: "Toyota",
    model: "Yaris Hybrid",
    grade: "Hybrid X",
    title: "Toyota Yaris Hybrid X",
    type: "Hatchback",
    year: 2021,
    registered: "March 2021",
    mileageKm: 34373,
    mileage: "34,373 km",
    fuel: "Hybrid (petrol)",
    transmission: "Automatic (CVT)",
    drive: "2WD (front)",
    engine: "1.5L (1,500 cc) hybrid",
    chassis: "MXPH10",
    seats: 5,
    color: "White",
    steering: "Right-hand drive",
    auctionGrade: "4 (exterior C / interior B)",
    badge: "Fuel saver",
    price: null,
    summary:
      "The fourth-generation Yaris Hybrid is Toyota's compact fuel-sipper, with Toyota Safety Sense, a back camera and a roomy hatch. Clean white, one of the most efficient cars you can buy.",
    highlights: ["Hybrid, up to ~36 km/L", "Toyota Safety Sense", "Back camera", "Compact 5-seater"],
    features: [
      "Hybrid system (1.5L engine + electric motor)",
      "Toyota Safety Sense",
      "Back camera",
      "Touchscreen display audio",
      "ABS and airbags",
      "Power steering and windows",
      "Automatic air conditioning",
      "Split-folding rear seat",
    ],
    specs: [
      ["Make / model", "Toyota Yaris Hybrid"],
      ["Grade", "Hybrid X"],
      ["Chassis code", "6AA-MXPH10"],
      ["First registered", "March 2021"],
      ["Mileage", "34,373 km (sheet)"],
      ["Engine", "1.5L 3-cyl petrol hybrid, M15A-FXE"],
      ["Transmission", "Automatic (CVT)"],
      ["Drive", "2WD (front)"],
      ["Seats", "5"],
      ["Fuel economy", "Up to ~36 km/L, WLTC (factory)"],
      ["Colour", "White (040)"],
      ["Steering", "Right-hand drive"],
      ["Auction grade", "4 / exterior C / interior B"],
    ],
    photos: cars("toyota-yaris-hybrid-x-2021", [
      ["Toyota Yaris Hybrid in white, front three-quarter view"],
      ["Yaris Hybrid front view"],
      ["Yaris Hybrid rear three-quarter view"],
      ["Yaris Hybrid rear view with black tailgate trim"],
      ["Yaris Hybrid dashboard and steering wheel"],
      ["Yaris Hybrid driver seat"],
      ["Yaris Hybrid infotainment and climate controls"],
      ["Yaris Hybrid rear seat"],
      ["Yaris Hybrid boot with the rear seat folded"],
      ["Yaris Hybrid roof view"],
      ["Yaris Hybrid front wheel and tyre"],
      ["Japanese auction inspection sheet for the Yaris Hybrid", "sheet"],
    ]),
  },
  {
    id: "PT-003",
    slug: "toyota-prius-s-touring-selection-2020",
    make: "Toyota",
    model: "Prius",
    grade: "S Touring Selection",
    title: "Toyota Prius S Touring Selection",
    type: "Hatchback",
    year: 2020,
    registered: "November 2020",
    mileageKm: 50468,
    mileage: "50,468 km",
    fuel: "Hybrid (petrol)",
    transmission: "Automatic (CVT)",
    drive: "2WD (front)",
    engine: "1.8L (1,800 cc) hybrid",
    chassis: "ZVW51",
    seats: 5,
    color: "Pearl White",
    steering: "Right-hand drive",
    auctionGrade: "R (exterior B / interior B)",
    badge: "Leather interior",
    price: null,
    summary:
      "The facelifted fourth-generation Prius in Touring Selection trim: leather seats with seat heaters, adaptive cruise control, navigation and a back camera, in Pearl White. Repair history is noted on the auction sheet.",
    highlights: ["Leather and heated seats", "Cruise control", "Hybrid efficiency", "Navigation and camera"],
    features: [
      "Leather seats with seat heaters",
      "Cruise control",
      "Colour back camera",
      "Navigation and TV",
      "ETC (electronic toll) unit",
      "Toyota Safety Sense",
      "ABS and airbags",
      "Power steering and windows",
      "Automatic air conditioning",
      "Multifunction steering wheel",
    ],
    specs: [
      ["Make / model", "Toyota Prius"],
      ["Grade", "S Touring Selection"],
      ["Chassis code", "6AA-ZVW51"],
      ["First registered", "November 2020"],
      ["Mileage", "50,468 km (sheet)"],
      ["Engine", "1.8L petrol hybrid, 2ZR-FXE"],
      ["Transmission", "Automatic (CVT)"],
      ["Drive", "2WD (front)"],
      ["Seats", "5"],
      ["Colour", "Pearl White (089)"],
      ["Steering", "Right-hand drive"],
      ["Auction grade", "R (repair history) / exterior B / interior B"],
    ],
    photos: cars("toyota-prius-s-touring-selection-2020", [
      ["Toyota Prius in Pearl White, front three-quarter view"],
      ["Prius front three-quarter view in the showroom"],
      ["Prius headlight and front bumper detail"],
      ["Prius rear view with LED tail lamps"],
      ["Prius rear view, second angle"],
      ["Prius rear quarter and tail lamp detail"],
      ["Prius steering wheel and instrument cluster"],
      ["Prius dashboard and navigation screen"],
      ["Prius leather driver seat"],
      ["Prius leather rear seat"],
      ["Prius roof view"],
      ["Japanese auction inspection sheet for the Prius", "sheet"],
    ]),
  },
  {
    id: "PT-004",
    slug: "toyota-sienta-hybrid-2017",
    make: "Toyota",
    model: "Sienta Hybrid",
    grade: "Hybrid",
    title: "Toyota Sienta Hybrid",
    type: "Minivan",
    year: 2017,
    registered: "2017",
    mileageKm: null,
    mileage: "On request",
    fuel: "Hybrid (petrol)",
    transmission: "Automatic (CVT)",
    drive: "2WD (front)",
    engine: "1.5L (1,500 cc) hybrid",
    chassis: "NHP170",
    seats: 7,
    color: "Silver",
    steering: "Right-hand drive",
    auctionGrade: "Sheet on request",
    badge: "Family 7-seater",
    price: null,
    summary:
      "A compact seven-seat family hybrid with sliding rear doors, a three-row layout and a leather-look interior. Silver, easy to park and very economical.",
    highlights: ["7-seat family hybrid", "Sliding rear doors", "Leather-look seats", "Compact and economical"],
    features: [
      "Hybrid system (1.5L engine + electric motor)",
      "Seven-seat, three-row layout",
      "Sliding rear doors",
      "Navigation display",
      "Leather-look seat trim",
      "Power steering and windows",
      "Automatic air conditioning",
      "Fold-flat third row",
    ],
    specs: [
      ["Make / model", "Toyota Sienta Hybrid"],
      ["Chassis code", "DAA-NHP170 (typical for this model)"],
      ["Model year", "2017"],
      ["Mileage", "On request"],
      ["Engine", "1.5L petrol hybrid, 1NZ-FXE"],
      ["Transmission", "Automatic (CVT)"],
      ["Drive", "2WD (front)"],
      ["Seats", "7"],
      ["Colour", "Silver"],
      ["Steering", "Right-hand drive"],
    ],
    photos: cars("toyota-sienta-hybrid-2017", [
      ["Toyota Sienta Hybrid in silver, front three-quarter view"],
      ["Sienta Hybrid front three-quarter view"],
      ["Sienta Hybrid rear three-quarter view"],
      ["Sienta Hybrid rear view with sliding door"],
      ["Sienta Hybrid dashboard and steering wheel"],
      ["Sienta Hybrid front seat"],
      ["Sienta Hybrid gear selector and navigation"],
      ["Sienta Hybrid second-row seat"],
      ["Sienta Hybrid third row and cargo area"],
      ["Sienta Hybrid roof view"],
      ["Sienta Hybrid front wheel and tyre"],
    ]),
  },
];

export const VEHICLE_TYPES = ["All", ...Array.from(new Set(VEHICLES.map((v) => v.type)))];

export function getVehicleBySlug(slug) {
  return VEHICLES.find((v) => v.slug === slug);
}

export const coverOf = (v) => v.photos[0];
