import { pexelsImg } from "@/lib/site";

// Sample stock, illustrated with real representative photos (Pexels,
// freely licensed for hotlinking) of the same vehicle type until real yard
// photos are supplied. Replace title/specs/price/img with real inventory as
// it changes — see README.md for details. `slug` powers each vehicle's own
// detail page and JSON-LD, so keep it unique and URL-safe.

export const VEHICLES = [
  {
    id: "v1",
    slug: "toyota-land-cruiser-prado",
    title: "Toyota Land Cruiser Prado",
    category: "cars",
    year: "2016",
    mileage: "78,000 km",
    fuel: "Diesel",
    transmission: "Automatic",
    price: "Contact for Price",
    icon: "car",
    img: pexelsImg(19410452, 900),
    imgAlt: "White SUV, representative of the Toyota Land Cruiser Prado",
  },
  {
    id: "v2",
    slug: "toyota-hiace-van-super-gl",
    title: "Toyota Hiace Van (Super GL)",
    category: "cars",
    year: "2015",
    mileage: "95,000 km",
    fuel: "Diesel",
    transmission: "Manual",
    price: "Contact for Price",
    icon: "van",
    img: pexelsImg(9115461, 900),
    imgAlt: "White cargo van, representative of the Toyota Hiace Super GL",
  },
  {
    id: "v11",
    slug: "nissan-caravan-cargo-van",
    title: "Nissan Caravan Cargo Van",
    category: "cars",
    year: "2017",
    mileage: "61,000 km",
    fuel: "Petrol",
    transmission: "Automatic",
    price: "Contact for Price",
    icon: "van",
    img: pexelsImg(9577104, 900),
    imgAlt: "White van, representative of the Nissan Caravan",
  },
  {
    id: "v3",
    slug: "isuzu-elf-dropside-cargo-truck",
    title: "Isuzu Elf Dropside Cargo Truck",
    category: "trucks",
    year: "2014",
    mileage: "110,000 km",
    fuel: "Diesel",
    transmission: "Manual",
    price: "Contact for Price",
    icon: "truck",
    img: pexelsImg(2449454, 900),
    imgAlt: "White cargo truck, representative of the Isuzu Elf",
  },
  {
    id: "v4",
    slug: "mitsubishi-fuso-canter-box-truck",
    title: "Mitsubishi Fuso Canter Box Truck",
    category: "trucks",
    year: "2013",
    mileage: "128,000 km",
    fuel: "Diesel",
    transmission: "Manual",
    price: "Contact for Price",
    icon: "dumptruck",
    img: pexelsImg(193667, 900),
    imgAlt: "White box truck, representative of the Mitsubishi Fuso Canter",
  },
  {
    id: "v12",
    slug: "ud-trucks-nissan-diesel-cargo-truck",
    title: "UD Trucks (Nissan Diesel) Cargo Truck",
    category: "trucks",
    year: "2012",
    mileage: "135,000 km",
    fuel: "Diesel",
    transmission: "Manual",
    price: "Contact for Price",
    icon: "truck",
    img: pexelsImg(2199293, 900),
    imgAlt: "White cargo truck, representative of UD Trucks / Nissan Diesel",
  },
  {
    id: "v5",
    slug: "hino-liesse-ii-mini-bus",
    title: "Hino Liesse II Mini Bus",
    category: "buses",
    year: "2012",
    mileage: "142,000 km",
    fuel: "Diesel",
    transmission: "Automatic",
    price: "Contact for Price",
    icon: "bus",
    img: pexelsImg(6761064, 900),
    imgAlt: "Mini bus, representative of the Hino Liesse II",
  },
  {
    id: "v6",
    slug: "komatsu-hydraulic-excavator",
    title: "Komatsu Hydraulic Excavator",
    category: "machinery",
    year: "2011",
    mileage: "6,200 hrs",
    fuel: "Diesel",
    transmission: "-",
    price: "Contact for Price",
    icon: "excavator",
    img: pexelsImg(13098128, 900),
    imgAlt: "Excavator at a construction site, representative of the Komatsu excavator",
  },
  {
    id: "v7",
    slug: "kubota-wheel-loader-backhoe",
    title: "Kubota Wheel Loader / Backhoe",
    category: "machinery",
    year: "2013",
    mileage: "4,800 hrs",
    fuel: "Diesel",
    transmission: "-",
    price: "Contact for Price",
    icon: "loader",
    img: pexelsImg(5125782, 900),
    imgAlt: "Yellow wheel loader, representative of the Kubota loader/backhoe",
  },
  {
    id: "v8",
    slug: "industrial-diesel-generator-set",
    title: "Industrial Diesel Generator Set",
    category: "generators",
    year: "2015",
    mileage: "3,100 hrs",
    fuel: "Diesel",
    transmission: "-",
    price: "Contact for Price",
    icon: "generator",
    img: pexelsImg(5506052, 900),
    imgAlt: "Diesel engine, representative of an industrial generator set",
  },
  {
    id: "v9",
    slug: "yanmar-agricultural-tractor",
    title: "Yanmar Agricultural Tractor",
    category: "tractors",
    year: "2012",
    mileage: "3,900 hrs",
    fuel: "Diesel",
    transmission: "Manual",
    price: "Contact for Price",
    icon: "tractor",
    img: pexelsImg(2252618, 900),
    imgAlt: "Tractor in a field, representative of the Yanmar agricultural tractor",
  },
  {
    id: "v10",
    slug: "rice-combine-harvester",
    title: "Rice Combine Harvester",
    category: "tractors",
    year: "2010",
    mileage: "2,600 hrs",
    fuel: "Diesel",
    transmission: "Manual",
    price: "Contact for Price",
    icon: "tractor",
    img: pexelsImg(17075355, 900),
    imgAlt: "Combine harvester in a wheat field",
  },
];

export function getVehicleBySlug(slug) {
  return VEHICLES.find((v) => v.slug === slug);
}
